### ISSUE TITLE
Imputed variants

### ISSUE THREAD

**Issue by Deleetdk** [endrebak/TAPMAT-data#2]
Some GWASs use imputed variants as well. I'm not sure if these are covered in 1kg or if we would have to impute them first and then derive the population frequencies. What are we doing about this issue?

**Comment by endrebak** [comment]
1000 genomes is very rich in data. Perhaps there are datasets with even more variants, but I think most people use 1000 genomes to impute their data, not the other way around. 

If there are datasets with more data we should just use those instead of imputing 1kg.

Of course, [even bigger datasets](http://www.genomicsengland.co.uk/the-100000-genomes-project/) will arrive.
